MK_CFG_DIR = /home/y/share/make_cfg
include $(MK_CFG_DIR)/make.defs

LIBNAME = nprocinfo
LIBVERSION=1
CSRC = procinfo.c

WARN +=
OPPFLAGS += -I/home/y/include/ncore
DEPOBJS = 
LDFLAGS = -L/home/y/lib
LDLIBS = -lncore

include $(MK_CFG_DIR)/make.rules
