MK_CFG_DIR = /home/z/share/make_cfg
include $(MK_CFG_DIR)/make.defs

LIBNAME = nprocinfo
LIBVERSION=1
CSRC = procinfo.c

WARN +=
OPPFLAGS += -I/home/z/include/ncore
DEPOBJS = 
LDFLAGS = -L/home/z/lib
LDLIBS = -lncore

include $(MK_CFG_DIR)/make.rules
